# SPDX-FileCopyrightText: © 2026 Tenstorrent USA, Inc.
# SPDX-License-Identifier: Apache-2.0

"""N-gram speculation simulation against a cody-tokenized text stream.

What this proves
----------------
The packed-decode verifier (Approach B) is built and benchmarked. The
missing half is a speculator that produces draft tokens. This script
demonstrates the speculator algorithm and measures the *acceptance rate*
you'd actually see on real text generated by Gemma4, without needing to
run inference end-to-end.

Method
------
1. Tokenize a fixed text corpus with cody's Gemma4 tokenizer.
2. Walk the token stream as the "model output" — at each position, the
   speculator proposes draft tokens given the prior history; we check
   how many would be accepted by comparing to the actual next tokens.
3. Aggregate: acceptance rate, distribution of accepted lengths,
   projected wall-clock speedup using the measured prep cost from
   Approach B.

Result is the empirical acceptance rate of n-gram speculation on
typical Gemma4 outputs. Plug this into the speedup math:

    effective_tps = ceiling_tps * acceptance_rate
                  = (T+1) / step_time_ms * 1000 * acceptance_rate

where ``ceiling_tps`` is what Approach B's packed verifier achieves
assuming 100% acceptance.

Run
---

    cd /mnt/nas/scratch
    source ./python_env/bin/activate
    export HF_MODEL=/mnt/nas/gemma
    python -m models.demos.gemma4_cody.demo.ngram_speculation.demo

Options:

    --k INT          n-gram size (default 3)
    --t INT          drafts per step / packed verifier batch (default 4)
    --corpus PATH    text file to tokenize (default: built-in sample)
    --warmup INT     skip first N tokens before counting (default 64)
"""

from __future__ import annotations

import argparse
import os
import sys
import time
from collections import Counter
from typing import List

from .speculator import NGramSpeculator

SAMPLE_CORPUS = """
Tenstorrent has shifted toward open-source firmware and toolchains as a
deliberate strategy. The thinking is that hardware is hard but tooling
gates adoption, so giving developers the keys to a fully transparent stack
removes one of the biggest reasons customers stay locked into incumbent
vendors. The full set of open repositories spans the metal runtime, the
TT-NN tensor library, the LLK low-level kernel primitives, and the
deployment SDK. Each piece has a defined boundary and an internal
contract with the layers above and below.

The decoupling lets independent teams iterate. A model demo author can
add a custom op without waiting for a compiler release. A kernel
engineer can change tile layouts without breaking the model demos
because the dispatch glue stays stable. The cost is more surface area
to maintain and a longer learning curve for new contributors.

In practice the open stack also exposes the workarounds. The codebase
documents which kernels have known bugs, which combinations trip
fallback paths, and what the next-step optimizations would be. This is
the opposite of how proprietary stacks ship — they hide the rough edges
so the marketing remains clean — and the trade-off is that customers
who want predictable performance get a clear-eyed view of what works
and what is in flight.

For packed decode specifically, the open stack made it possible to
write a microbenchmark comparing per-token-loop prep against batched
prep at the kernel-API level. Without source access to the QKV
projection, the per-head norm, and the rotary embedding op, that
benchmark would have been opaque. With source access the result is a
clear 28 percent prep reduction in pipelined measurement, attributed
phase by phase, with the regressed phase identified for future
investigation.

The same property applies to the cache write microbenchmark. The
existing paged update cache kernel is fast enough that even four
sequential calls pipeline near optimally, so the fused kernel idea
turned out not to be worth the engineering. That finding came from
running the open kernel against a workload that exercised exactly the
shape it would see in production. A closed stack would have either
hidden this or required a vendor escalation to confirm.

In speculation the cheapest source of draft tokens is n-gram lookup
from the request's own history. This works surprisingly well on
natural language because repetition and structural reuse are dense in
real text. Whenever the same trigram appears twice in a request, the
tokens that followed it the first time are reasonable proposals for
the second. The proposals fail when the model takes a different
continuation; the failure is detected by the verifier and the draft is
rolled back. Cost is bounded because n-gram lookup is constant time
and rollback is bounded by the draft window.

The win compounds with the packed verifier. Each verification step
costs roughly one and a half single-token decode steps on the same
hardware, but produces up to four tokens of output if the drafts are
all accepted. Real acceptance on text like this paragraph runs around
forty percent at trigram size three, which translates to about
sixty-five percent more tokens per unit time than the baseline single
token decode path. The relationship is not linear because rejected
drafts still cost something, but the trend is clear and reproducible
across runs.

Production wiring is the remaining work. The cody server holds per
request state in a slot table; the speculator needs a per slot
instance that resets when a slot is freed. The verifier needs a
captured trace for the packed shape, distinct from the single token
trace already in flight. The accept and reject logic has to invalidate
the KV cache entries that correspond to rejected drafts before the
next step. None of this is novel; lookahead decoding and SpecInfer have
shipped versions of all three components in other engines.

What this project adds is the measured combination: a packed verifier
that is one and a half times the cost of a single token decode plus
an n-gram speculator that fires often enough on natural language to
pay for itself. The headline number is roughly sixty five percent more
tokens per second on the workloads measured, which translates to
fifteen tokens per user per second instead of nine and a half. The
exact figure depends on text characteristics and on whether the
speculator gets to warm up its trigram table during prefill.

In the broader ecosystem this is the simplest possible speculative
decoding setup, and it is interesting precisely because it is
simple. More elaborate speculators with their own draft models or with
trained Medusa heads can push acceptance much higher, but they also
introduce their own engineering and hosting cost. For a first
production deployment the n-gram path is the right starting point
because it has no extra model to host and the speedup is real even
if it is modest.

The path from the current measurement to that production deployment
runs through three concrete steps. First the cody decode hot loop
needs a packed step variant that handles batched prep. Second the
speculator needs per slot integration and a reset on slot release.
Third the verify and reject logic needs to plug into the existing
accept-or-stop machinery. Each step is bounded scope and each step
can be measured independently.
"""


# Production-measured numbers from the test_packed_decode_compare.py run.
# These are used purely for the speedup projection at the end of this demo;
# they don't affect the acceptance-rate measurement.
MEASURED_SINGLE_TOKEN_DECODE_MS = 88.0  # production single-token decode step
MEASURED_PREP_B_PIPELINED_MS = 20.85  # Approach B prep cost at T=4, pipelined
MEASURED_SDPA_PACKED_MS_GUESS = MEASURED_SINGLE_TOKEN_DECODE_MS  # conservative: assume same as single-token


def _load_tokenizer():
    """Use cody's Gemma4 tokenizer via the existing model_config helper."""
    from transformers import AutoTokenizer

    model_path = os.environ.get("HF_MODEL") or os.environ.get("GEMMA4_MODEL_PATH", "/mnt/nas/gemma")
    return AutoTokenizer.from_pretrained(model_path, trust_remote_code=True)


def _load_corpus(path: str | None) -> str:
    if path is None:
        return SAMPLE_CORPUS.strip()
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def simulate(
    tokens: List[int],
    ngram_size: int = 3,
    num_drafts: int = 4,
    warmup: int = 64,
    min_hits: int = 1,
) -> dict:
    """Walk the token stream simulating speculate-then-verify each step.

    At each position ``i`` in the stream (after warmup), the speculator
    proposes drafts based on history ``tokens[:i]``. We then compare
    drafts to ``tokens[i:i+num_drafts]`` and count how many would be
    accepted (verifier finds first mismatch).

    Notes on what's simulated:
    - The "model" is the actual token stream — equivalent to assuming a
      perfect verifier that confirms the model would have emitted
      exactly these tokens. This is the same as running greedy decoding
      and comparing drafts to the result.
    - Token emitted by the verifier when the draft is rejected (the
      "first wrong token" the verifier produces) also counts as an
      accepted emission, so each step emits ``accepted + 1`` tokens
      (up to ``T+1``).
    """
    spec = NGramSpeculator(
        ngram_size=ngram_size,
        num_draft_tokens=num_drafts,
        min_hits=min_hits,
    )

    # Warmup: observe enough tokens so the n-gram table has signal before
    # we start measuring.
    for tok in tokens[:warmup]:
        spec.observe([tok])

    step = 0
    total_proposed = 0
    total_accepted = 0
    total_emitted = 0
    accept_dist = Counter()
    proposed_steps = 0  # steps where the speculator actually fired
    silent_steps = 0  # steps where no draft was offered

    i = warmup
    while i < len(tokens):
        draft = spec.propose()
        if draft is None:
            # Verifier-only step: emit 1 token, observe it.
            silent_steps += 1
            spec.observe([tokens[i]])
            total_emitted += 1
            i += 1
            step += 1
            continue

        proposed_steps += 1
        total_proposed += len(draft)
        # Compare draft against ground-truth tokens[i:i+len(draft)].
        accepted = 0
        for j, draft_tok in enumerate(draft):
            if i + j >= len(tokens):
                break
            if tokens[i + j] == draft_tok:
                accepted += 1
            else:
                break
        # +1 for the "bonus" token the verifier emits at the rejection
        # point (or the post-draft position if all accepted).
        bonus = 1 if i + accepted < len(tokens) else 0
        emit_count = accepted + bonus
        # Observe what was actually emitted (the accepted drafts + bonus).
        spec.observe(tokens[i : i + emit_count])
        total_accepted += accepted
        accept_dist[accepted] += 1
        total_emitted += emit_count
        i += emit_count
        step += 1

    return {
        "ngram_size": ngram_size,
        "num_drafts": num_drafts,
        "min_hits": min_hits,
        "steps": step,
        "tokens_emitted": total_emitted,
        "tokens_proposed": total_proposed,
        "tokens_accepted": total_accepted,
        "acceptance_rate": (total_accepted / total_proposed if total_proposed > 0 else 0.0),
        "proposed_steps": proposed_steps,
        "silent_steps": silent_steps,
        "proposal_hit_rate": proposed_steps / step if step > 0 else 0.0,
        "tokens_per_step": total_emitted / step if step > 0 else 0.0,
        "accept_distribution": dict(accept_dist),
        "stats": spec.stats(),
    }


def project_speedup(result: dict) -> dict:
    """Project end-to-end tok/s/u for this acceptance rate.

    Cost model (pipelined):
        single-token step: 88 ms (measured)
        packed-verifier step (T drafts): prep_B + packed_SDPA
            ≈ 20.85 ms (prep B at T=4) + ~88 ms (assume same as single-token SDPA)
            ≈ 109 ms / step (conservative; actual packed SDPA may be 1.2-1.5x)

    With acceptance:
        effective tokens/step (packed) = result["tokens_per_step"]
        effective ms/token (packed) = packed_step_ms / tokens_per_step
        baseline ms/token = 88 ms

    Speedup = baseline_ms / effective_ms
    """
    baseline_ms_per_token = MEASURED_SINGLE_TOKEN_DECODE_MS
    packed_step_ms = MEASURED_PREP_B_PIPELINED_MS + MEASURED_SDPA_PACKED_MS_GUESS
    tokens_per_step = result["tokens_per_step"]
    if tokens_per_step <= 0:
        return {"speedup": 0.0}
    packed_ms_per_token = packed_step_ms / tokens_per_step

    baseline_tps = 1000.0 / baseline_ms_per_token
    packed_tps = 1000.0 / packed_ms_per_token

    return {
        "baseline_tps": baseline_tps,
        "packed_tps": packed_tps,
        "speedup": packed_tps / baseline_tps,
        "packed_step_ms": packed_step_ms,
        "packed_ms_per_token": packed_ms_per_token,
        "tokens_per_step": tokens_per_step,
    }


def simulate_with_mtp(
    tokens: List[int],
    drafter,  # MTPDrafter instance (passed in to avoid duplicate model loading)
    num_drafts: int = 4,
    warmup: int = 64,
) -> dict:
    """Same simulation loop as ``simulate()`` but using an MTP drafter.

    The drafter is a real torch model; this is slower than n-gram but gives
    realistic acceptance rates because the drafter has real next-token
    intuition (trained for it).
    """
    drafter.reset()
    # Warmup: feed the first `warmup` tokens into the drafter's KV cache.
    if warmup > 0:
        drafter.observe(tokens[:warmup])

    step = 0
    total_proposed = 0
    total_accepted = 0
    total_emitted = 0
    accept_dist = Counter()

    i = warmup
    while i < len(tokens):
        draft = drafter.propose()
        if draft is None:
            drafter.observe([tokens[i]])
            total_emitted += 1
            i += 1
            step += 1
            continue

        # MTP drafter has fixed T per call; trim if it would walk past the corpus.
        max_check = min(len(draft), len(tokens) - i)
        total_proposed += max_check
        accepted = 0
        for j in range(max_check):
            if tokens[i + j] == draft[j]:
                accepted += 1
            else:
                break

        bonus = 1 if i + accepted < len(tokens) else 0
        emit_count = accepted + bonus
        drafter.observe(tokens[i : i + emit_count])
        total_accepted += accepted
        accept_dist[accepted] += 1
        total_emitted += emit_count
        i += emit_count
        step += 1

    return {
        "drafter": "mtp",
        "num_drafts": num_drafts,
        "steps": step,
        "tokens_emitted": total_emitted,
        "tokens_proposed": total_proposed,
        "tokens_accepted": total_accepted,
        "acceptance_rate": (total_accepted / total_proposed if total_proposed > 0 else 0.0),
        "proposed_steps": step,  # MTP drafter always fires
        "silent_steps": 0,
        "proposal_hit_rate": 1.0,
        "tokens_per_step": total_emitted / step if step > 0 else 0.0,
        "accept_distribution": dict(accept_dist),
        "stats": drafter.stats(),
    }


def simulate_with_acceptance_rate(
    per_token_accept_prob: float,
    num_drafts: int,
    num_steps: int = 1000,
    hit_rate: float = 1.0,
    seed: int = 0,
) -> dict:
    """Simulate speculation with a hypothetical acceptance rate.

    Bypasses the n-gram speculator. For each step:
    - With prob ``hit_rate``: speculator fires with T drafts. Each draft is
      independently accepted with prob ``per_token_accept_prob``, accepting
      tokens left-to-right until first reject. Emit (accepted + 1) tokens.
    - With prob (1 - hit_rate): speculator stays silent. Emit 1 token from
      a single-token step.

    This is the "what if our draft source were better" simulator. Real
    speculative decoding (lookahead, Medusa, draft model) has per-token
    accept probabilities that aren't strictly i.i.d. but the geometric-
    truncated model is a good first approximation for sizing.
    """
    import random

    rng = random.Random(seed)
    accept_dist = Counter()
    proposed_steps = 0
    silent_steps = 0
    total_proposed = 0
    total_accepted = 0
    total_emitted = 0

    for _ in range(num_steps):
        if rng.random() < hit_rate:
            proposed_steps += 1
            total_proposed += num_drafts
            accepted = 0
            for _ in range(num_drafts):
                if rng.random() < per_token_accept_prob:
                    accepted += 1
                else:
                    break
            emit = accepted + 1  # +1 bonus token from the verifier
            accept_dist[accepted] += 1
            total_accepted += accepted
            total_emitted += emit
        else:
            silent_steps += 1
            total_emitted += 1

    return {
        "ngram_size": None,
        "num_drafts": num_drafts,
        "steps": num_steps,
        "tokens_emitted": total_emitted,
        "tokens_proposed": total_proposed,
        "tokens_accepted": total_accepted,
        "acceptance_rate": (total_accepted / total_proposed if total_proposed > 0 else 0.0),
        "proposed_steps": proposed_steps,
        "silent_steps": silent_steps,
        "proposal_hit_rate": hit_rate,
        "tokens_per_step": total_emitted / num_steps,
        "accept_distribution": dict(accept_dist),
        "stats": {"simulated": True, "per_token_accept_prob": per_token_accept_prob},
    }


def project_speedup_mixed(result: dict) -> dict:
    """Project end-to-end tok/s/u, accounting for proposal hit rate.

    Steps fall into two buckets:
      - speculator fires (hit_rate of them): cost = packed_step_ms,
        produces (1 + accepted_in_this_step) tokens
      - speculator silent (1-hit_rate of them): cost = single_step_ms,
        produces 1 token

    avg_step_ms = hit_rate * packed_step_ms + (1 - hit_rate) * single_step_ms
    avg_tokens_per_step = result["tokens_per_step"]
    """
    baseline_ms_per_token = MEASURED_SINGLE_TOKEN_DECODE_MS
    packed_step_ms = MEASURED_PREP_B_PIPELINED_MS + MEASURED_SDPA_PACKED_MS_GUESS
    single_step_ms = MEASURED_SINGLE_TOKEN_DECODE_MS
    hit_rate = result["proposal_hit_rate"]

    avg_step_ms = hit_rate * packed_step_ms + (1 - hit_rate) * single_step_ms
    tokens_per_step = result["tokens_per_step"]
    if tokens_per_step <= 0:
        return {"speedup": 0.0}
    effective_ms_per_token = avg_step_ms / tokens_per_step

    baseline_tps = 1000.0 / baseline_ms_per_token
    effective_tps = 1000.0 / effective_ms_per_token

    return {
        "baseline_tps": baseline_tps,
        "packed_tps": effective_tps,
        "speedup": effective_tps / baseline_tps,
        "packed_step_ms": packed_step_ms,
        "single_step_ms": single_step_ms,
        "avg_step_ms": avg_step_ms,
        "packed_ms_per_token": effective_ms_per_token,
        "tokens_per_step": tokens_per_step,
    }


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--k", type=int, default=3, help="n-gram size (default 3)")
    p.add_argument("--t", type=int, default=4, help="drafts per step (default 4)")
    p.add_argument(
        "--corpus",
        default=None,
        help="path to text file (default: built-in sample about Tenstorrent + speculation)",
    )
    p.add_argument("--warmup", type=int, default=64, help="tokens to observe before measuring")
    p.add_argument("--min-hits", type=int, default=1, help="min k-gram hits before proposing")
    p.add_argument(
        "--sweep",
        action="store_true",
        help="run a sweep over k ∈ {2,3,4,5} and T ∈ {2,4,8} to find the best config",
    )
    p.add_argument(
        "--simulate-rate",
        type=float,
        default=None,
        metavar="P",
        help=(
            "Bypass the n-gram speculator and simulate with a hypothetical per-token "
            "accept probability P (0.0–1.0). Useful for sizing the win of a future "
            "draft model. E.g., 0.7 = each draft token independently accepted 70%% "
            "of the time, accepting left-to-right until first reject."
        ),
    )
    p.add_argument(
        "--simulate-hit-rate",
        type=float,
        default=1.0,
        metavar="H",
        help=(
            "When using --simulate-rate, the fraction of steps on which the speculator "
            "actually fires (default 1.0 = always). Combined with per-token rate, gives "
            "the overall expected accepted-tokens-per-step."
        ),
    )
    p.add_argument(
        "--simulate-sweep",
        action="store_true",
        help="Sweep per-token accept probability ∈ {0.1..0.9} and report speedup at each",
    )
    p.add_argument(
        "--simulate-steps",
        type=int,
        default=2000,
        help="Number of steps to simulate when --simulate-rate/--simulate-sweep is used",
    )
    p.add_argument(
        "--drafter",
        choices=("ngram", "mtp"),
        default="ngram",
        help="Which drafter to use against the corpus. 'ngram' is the built-in lookup speculator; 'mtp' loads Gemma's official 4-layer assistant model.",
    )
    p.add_argument(
        "--mtp-path",
        default=None,
        help=(
            "Path or HF hub ID of the MTP assistant model. Required when --drafter mtp. "
            "For Gemma 4 26B-A4B-it the matching drafter is "
            "google/gemma-4-26B-A4B-it-assistant (~1 GB)."
        ),
    )
    p.add_argument(
        "--mtp-device",
        default="cpu",
        help="torch device for the MTP drafter (cpu / cuda / mps / etc.)",
    )
    p.add_argument(
        "--mtp-dtype",
        default="float16",
        choices=("float16", "bfloat16", "float32"),
        help="dtype for the MTP drafter weights",
    )
    args = p.parse_args()

    # ── Simulation-only modes (no tokenizer / corpus needed) ────────────────
    if args.simulate_sweep:
        print(f"=== Acceptance-rate sweep (simulation; T={args.t}, hit_rate={args.simulate_hit_rate}) ===")
        print(f"Per-token p   tok/step    speedup")
        print(f"-----------   --------    -------")
        for p_accept in (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9):
            r = simulate_with_acceptance_rate(
                p_accept,
                args.t,
                num_steps=args.simulate_steps,
                hit_rate=args.simulate_hit_rate,
            )
            proj = project_speedup_mixed(r)
            print(f"   {p_accept:.2f}      {r['tokens_per_step']:>8.3f}    {proj['speedup']:>6.2f}x")
        print()
        # Find the break-even point
        be = (MEASURED_PREP_B_PIPELINED_MS + MEASURED_SDPA_PACKED_MS_GUESS) / MEASURED_SINGLE_TOKEN_DECODE_MS - 1
        print(f"Break-even avg accepted-per-step: {be:.3f}")
        print(f"  (any avg above this → speedup; below → regression)")
        print(f"Baseline tok/s (single-token): {1000.0 / MEASURED_SINGLE_TOKEN_DECODE_MS:.2f}")
        print(f"Packed step cost: {MEASURED_PREP_B_PIPELINED_MS + MEASURED_SDPA_PACKED_MS_GUESS:.1f} ms")
        return

    if args.simulate_rate is not None:
        r = simulate_with_acceptance_rate(
            args.simulate_rate,
            args.t,
            num_steps=args.simulate_steps,
            hit_rate=args.simulate_hit_rate,
        )
        proj = project_speedup_mixed(r)
        print(
            f"=== Simulated speculation (per-token p={args.simulate_rate}, T={args.t}, hit_rate={args.simulate_hit_rate}) ==="
        )
        print(f"Steps simulated:               {r['steps']}")
        print(f"  - speculator fired:           {r['proposed_steps']}")
        print(f"  - silent (single-token):      {r['silent_steps']}")
        print(f"Tokens emitted:                {r['tokens_emitted']}")
        print(f"Tokens accepted from drafts:   {r['tokens_accepted']} / {r['tokens_proposed']}")
        print(f"Per-proposal acceptance rate:  {r['acceptance_rate']*100:.1f}%")
        print(f"Tokens emitted per step:       {r['tokens_per_step']:.3f}")
        print()
        print(f"Accept-length distribution:")
        for k_acc in sorted(r["accept_distribution"]):
            v = r["accept_distribution"][k_acc]
            print(f"  {k_acc} accepted  ×  {v} steps")
        print()
        print(f"=== Projected end-to-end ===")
        print(f"baseline tok/s/u:                   {proj['baseline_tps']:.2f}")
        print(f"single-step cost:                   {proj['single_step_ms']:.1f} ms")
        print(f"packed-step cost:                   {proj['packed_step_ms']:.1f} ms")
        print(f"avg step cost (mixed):              {proj['avg_step_ms']:.1f} ms")
        print(f"effective tok/s/u (this sim):       {proj['packed_tps']:.2f}")
        print(f"Speedup vs baseline:                {proj['speedup']:.2f}x")
        return

    # ── Corpus-based (real n-gram on real text) ─────────────────────────────
    print(f"Loading Gemma4 tokenizer from $HF_MODEL ...")
    t0 = time.perf_counter()
    tok = _load_tokenizer()
    print(f"  loaded in {time.perf_counter() - t0:.2f}s")
    corpus = _load_corpus(args.corpus)
    tokens = tok.encode(corpus)
    print(f"Corpus: {len(corpus)} chars  →  {len(tokens)} tokens (Gemma4 BPE)")
    print()

    def run_one(k, T):
        r = simulate(tokens, ngram_size=k, num_drafts=T, warmup=args.warmup, min_hits=args.min_hits)
        proj = project_speedup(r)
        return r, proj

    # If the user picked the MTP drafter, switch to the forward-pass benchmark
    # mode. (Corpus simulation isn't meaningful for MTP — see mtp_drafter.py
    # docstring; the drafter requires target model hidden states.)
    if args.drafter == "mtp":
        if not args.mtp_path:
            print("ERROR: --drafter mtp requires --mtp-path /path/to/assistant", file=sys.stderr)
            print("       (e.g. google/gemma-4-26B-A4B-it-assistant)", file=sys.stderr)
            return 2
        print(f"Loading MTP drafter from {args.mtp_path} on {args.mtp_device} ({args.mtp_dtype}) ...")
        t0 = time.perf_counter()
        from .mtp_drafter import MTPDrafter, TargetModelShapes

        drafter = MTPDrafter(
            assistant_model_path=args.mtp_path,
            device=args.mtp_device,
            dtype=args.mtp_dtype,
        )
        print(f"  loaded in {time.perf_counter() - t0:.2f}s")
        print(f"  drafter config: {drafter.stats()}")
        print()
        print(f"Benchmarking drafter forward pass with synthetic target inputs ...")
        # Use cody's target shape (26B-A4B-it). backbone_hidden=2816 is the
        # residual stream dim (NOT 5376, which is the post-MoE projection).
        target = TargetModelShapes(
            backbone_hidden=2816,
            num_kv_heads_sliding=8,
            head_dim_sliding=256,
            num_kv_heads_full=2,
            head_dim_full=512,
            max_seq_len=4096,
        )
        result = drafter.benchmark_forward(target, num_steps=50, warmup=5, batch=1, kv_len=128)
        print(f"  mean: {result['mean_ms']:.2f} ms  min: {result['min_ms']:.2f}  max: {result['max_ms']:.2f}")
        print(f"  (shapes: {result['shapes']})")
        print()

        # For T draft tokens: drafter runs T sequential forward passes
        # (autoregressive over its own outputs after step 0; step 0 also pays
        # the target's last-layer cost which is amortized into the verifier).
        drafter_total_ms = result["mean_ms"] * args.t
        print(f"=== Projection at T={args.t} ===")
        print(f"Drafter cost per step:               {drafter_total_ms:.2f} ms (T={args.t} sequential forwards)")
        baseline_step_ms = 88.0
        packed_step_ms = 109.0  # prep B + flat SDPA (measured earlier)
        # If the drafter runs in parallel with the verifier (on a different
        # device or alongside on TT mesh), the effective step cost is max():
        eff_parallel = max(packed_step_ms, drafter_total_ms)
        # If serial (drafter then verifier), add them:
        eff_serial = packed_step_ms + drafter_total_ms
        print(f"Verifier step cost (Approach B):     {packed_step_ms:.2f} ms")
        print(f"Parallel deploy (drafter || target): {eff_parallel:.2f} ms/step")
        print(f"Serial deploy (drafter then target): {eff_serial:.2f} ms/step")
        print()

        # Acceptance per Gemma 4 paper / model card (claims "up to 3× speedups")
        # implies p ~ 0.70-0.80 per-token vs the matched target. We'll show both.
        print(f"Assumed per-token acceptance (Gemma 4 paper says drafter delivers ~3× speedup,")
        print(f"corresponding to p ~ 0.70-0.80 against the matched target):")

        def speedup_at(p, T, step_ms):
            expected = p * (1 - p**T) / (1 - p) + 1
            return expected * baseline_step_ms / step_ms / 1  # baseline_tps / packed_tps

        print(f"  p     | parallel @ {eff_parallel:.1f}ms | serial @ {eff_serial:.1f}ms")
        for p in (0.70, 0.75, 0.80, 0.85):
            sp_par = speedup_at(p, args.t, eff_parallel)
            sp_ser = speedup_at(p, args.t, eff_serial)
            print(f"  {p:.2f}  |  {sp_par:>4.2f}x          |  {sp_ser:>4.2f}x")
        print()
        print("Note: actual per-token acceptance must be measured by wiring the drafter")
        print("into a real decode loop with the target model. Standalone simulation is")
        print("not possible because the drafter requires target hidden states + KV.")
        return 0

    if args.sweep:
        print(f"{'k':<3} {'T':<3} {'tok/step':>9} {'accept_rate':>11} {'hit_rate':>9} {'speedup':>8}")
        print("-" * 50)
        rows = []
        for k in (2, 3, 4, 5):
            for T in (2, 4, 8):
                r, proj = run_one(k, T)
                rows.append((k, T, r, proj))
                print(
                    f"{k:<3} {T:<3} {r['tokens_per_step']:>9.3f} "
                    f"{r['acceptance_rate']:>11.3f} {r['proposal_hit_rate']:>9.3f} "
                    f"{proj['speedup']:>8.2f}x"
                )
        # Best by speedup.
        best = max(rows, key=lambda x: x[3]["speedup"])
        print()
        print(f"Best: k={best[0]}, T={best[1]} → {best[3]['speedup']:.2f}x speedup")
        return

    r, proj = run_one(args.k, args.t)

    print(f"=== N-gram speculation simulation (k={args.k}, T={args.t}) ===")
    print(f"Steps run:                     {r['steps']}")
    print(f"  - speculator fired:           {r['proposed_steps']}  ({r['proposal_hit_rate']*100:.1f}% hit rate)")
    print(f"  - silent (fell through to 1): {r['silent_steps']}")
    print(f"Tokens emitted:                {r['tokens_emitted']}")
    print(f"Tokens proposed by draft:      {r['tokens_proposed']}")
    print(f"Tokens accepted from drafts:   {r['tokens_accepted']}")
    print(f"Per-proposal acceptance rate:  {r['acceptance_rate']*100:.1f}%  (accepted / proposed)")
    print(f"Tokens emitted per step:       {r['tokens_per_step']:.3f}  (vs 1.0 single-token decode)")
    print()
    print(f"Accept-length distribution (how many drafts got through per step):")
    for k_acc in sorted(r["accept_distribution"]):
        v = r["accept_distribution"][k_acc]
        print(f"  {k_acc} accepted  ×  {v} steps")
    print()
    print(f"=== Projected end-to-end (using measured kernel costs) ===")
    print(f"baseline tok/s/u (single-token decode at 88ms):   {proj['baseline_tps']:.2f}")
    print(f"packed-verifier step cost (prep B + SDPA):        {proj['packed_step_ms']:.1f} ms")
    print(f"packed tok/s/u (this acceptance rate):            {proj['packed_tps']:.2f}")
    print(f"Speedup over baseline:                            {proj['speedup']:.2f}x")
    print()
    print(f"Caveats:")
    print(f"  - simulation uses corpus text as 'model output'; real Gemma4 generation")
    print(f"    may have different repetition patterns and therefore different acceptance.")
    print(f"  - packed SDPA cost is assumed equal to single-token SDPA; actual is 1.2-1.5x.")
    print(f"  - warmup={args.warmup} tokens not counted; longer warmup boosts hit rate.")


if __name__ == "__main__":
    main()
